# Generated by Django 6.0.4 on 2026-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='route_geometry',
            field=models.JSONField(blank=True, help_text='GeoJSON LineString geometry from routing API', null=True),
        ),
    ]
